### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/enigma2-openvision#37]
`Compiling dm820 image, please wait ...

Generating /home/atef/openvision-development-platform/build/env.source
Generating /home/atef/openvision-development-platform/build/conf/openvision.conf
Generating /home/atef/openvision-development-platform/build/conf/bblayers.conf
Generating /home/atef/openvision-development-platform/build/conf/local.conf
Building image for dm820
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
ERROR: ExpansionError during parsing /home/atef/openvision-development-platform/meta-openvision/recipes-multimedia/x264/x264_git.bb                                            | ETA:  0:03:00
Traceback (most recent call last):
  File "/home/atef/openvision-development-platform/bitbake/lib/bb/fetch2/__init__.py", line 1181, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f79be4c6400>, d=<bb.data_smart.DataSmart object at 0x7f79be56ca58>, name='default'):
         if srcrev == "AUTOINC":
    >        srcrev = ud.method.latest_revision(ud, d, name)
     
  File "/home/atef/openvision-development-platform/bitbake/lib/bb/fetch2/__init__.py", line 1596, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7f79be4c6400>, d=<bb.data_smart.DataSmart object at 0x7f79be56ca58>, name='default'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/atef/openvision-development-platform/bitbake/lib/bb/fetch2/git.py", line 631, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7f79be4c6400>, d=<bb.data_smart.DataSmart object at 0x7f79be56ca58>, name='default'):
             """
    >        output = self._lsremote(ud, d, "")
             # Tags of the form ^{} may not work, need to fallback to other form
  File "/home/atef/openvision-development-platform/bitbake/lib/bb/fetch2/git.py", line 620, in Git._lsremote(ud=<bb.fetch2.FetchData object at 0x7f79be4c6400>, d=<bb.data_smart.DataSmart object at 0x7f79be56ca58>, search=''):
                     bb.fetch2.check_network_access(d, cmd, repourl)
    >            output = runfetchcmd(cmd, d, True)
                 if not output:
  File "/home/atef/openvision-development-platform/bitbake/lib/bb/fetch2/__init__.py", line 898, in runfetchcmd(cmd='export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1464"; export SSH_AUTH_SOCK="/tmp/ssh-0gPMWNjSxpsx/agent.1379"; export PATH="/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/perl-native:/home/atef/openvision-development-platform/openembedded-core/scripts:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/mipsel-oe-linux:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/atef/openvision-development-platform/bitbake/bin:/home/atef/openvision-development-platform/build/tmp/hosttools"; export HOME="/home/atef"; git -c core.fsyncobjectfiles=0 ls-remote https://code.videolan.org/videolan/x264 ', d=<bb.data_smart.DataSmart object at 0x7f79be3d75f8>, quiet=True, cleanup=[], log=None, workdir=None):
     
    >        raise FetchError(error_message)
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1464"; export SSH_AUTH_SOCK="/tmp/ssh-0gPMWNjSxpsx/agent.1379"; export PATH="/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/perl-native:/home/atef/openvision-development-platform/openembedded-core/scripts:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/mipsel-oe-linux:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/x264/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/atef/openvision-development-platform/bitbake/bin:/home/atef/openvision-development-platform/build/tmp/hosttools"; export HOME="/home/atef"; git -c core.fsyncobjectfiles=0 ls-remote https://code.videolan.org/videolan/x264  failed with exit code 128, output:
fatal: unable to access 'https://code.videolan.org/videolan/x264/': gnutls_handshake() failed: Error in the pull function.

Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Makefile:98: recipe for target 'image' failed
make: *** [image] Error 1

Done, the compiled image is in build/tmp/deploy/images/dm820 folder!
It's a zipped file like openvision-enigma2-develop-english|multilanguage|extralanguage-9.3-r105-dm820.zip
atef@atef:~/openvision-development-platform$ 
`

**Comment by persianpros** [comment]
Fetch errors are not related to us.
